theme: jekyll-theme-minimal
title: Squirrel
description: The Linked Data Crawler
logo: <img src="https://hobbitdata.informatik.uni-leipzig.de/squirrel/squirrel-logo.png" align="center" height="248" width="244" > 
